# Generated by Django 3.1.6 on 2021-02-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0006_name_unique_per_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconnection',
            name='update_strategy',
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        'openwisp_controller.connection.connectors.openwrt.ssh.OpenWrt',
                        'OpenWRT SSH',
                    ),
                    (
                        'openwisp_controller.connection.connectors.openwrt.ssh.OpenWisp1',  # noqa
                        'OpenWISP 1.x SSH',
                    ),
                ],
                db_index=True,
                help_text='leave blank to determine automatically',
                max_length=128,
                verbose_name='update strategy',
            ),
        ),
    ]
